### ISSUE TITLE
Help needed?

### ISSUE THREAD

**Issue by Gpx** [glauberfc/dom-testing-library-website#1]
Hi there!

I'm one of the organizers of https://hacktoberfestbarcelona.com/

On October 21st we'll have a bunch of javascript developers working together on open source projects. I was thinking this website would be a very good exercise, especially for beginners.

Is this something you would be interested in? If so do you have a list of tasks that need to be done?

Thanks!

**Comment by glauberfc** [comment]
Oh, I'm sorry! Yes, I need help, but I don't have the list of tasks yet. I will do!

**Comment by Gpx** [comment]
Hey @glauberfc the event is now passed I'm going to close the issue. Still, if you want to make a list of tasks maybe someone will pick it up
